server {
    listen 80;
    server_name document.accurate-value.uz;

    root /root/pdf-scan-api/public;

    location / {
        proxy_pass http://127.0.0.1:3000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }

    location /favicon.ico {
        alias /root/pdf-scan-api/public/favicon.ico;
    }

    error_log /var/log/nginx/document_error.log;
    access_log /var/log/nginx/document_access.log;
}
