"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var express_1 = require("express");
var category_controller_1 = require("../controllers/category.controller");
var router = (0, express_1.Router)();
router.get("/", category_controller_1.default.getCategories);
router.get("/:id", category_controller_1.default.getCategory);
router.post("/create", category_controller_1.default.createCategory);
router.put("/:id", category_controller_1.default.updateCategory);
router.delete("/:id", category_controller_1.default.deleteCategory);
exports.default = router;
