"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var express_1 = require("express");
var document_controller_1 = require("../controllers/document.controller");
var user_controller_1 = require("../controllers/user.controller");
var router = (0, express_1.Router)();
router.get("/", document_controller_1.default.getDocuments);
router.get("/:id", document_controller_1.default.getDocument);
router.post("/create", document_controller_1.default.createDocument);
router.put("/update/:id", document_controller_1.default.updateDocument);
router.put("/change-status/:id", user_controller_1.default.checkRole, document_controller_1.default.changeStatus);
router.delete("/:id", document_controller_1.default.deleteDocument);
exports.default = router;
