"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var express_1 = require("express");
var files_controller_1 = require("../controllers/files.controller");
var multer_util_1 = require("../utils/multer.util");
var router = (0, express_1.Router)();
router.get("/", files_controller_1.default.getFiles);
router.get("/:id", files_controller_1.default.getFile);
router.get("/download/:id", files_controller_1.default.downloadFile);
router.post("/upload", multer_util_1.default.uploadFile, files_controller_1.default.createFile);
router.put("/:id", files_controller_1.default.updateFile);
router.delete("/:id", files_controller_1.default.deleteFile);
exports.default = router;
