"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var express_1 = require("express");
var qrcode_controller_1 = require("../controllers/qrcode.controller");
var files_controller_1 = require("../controllers/files.controller");
var qrcode_controller_2 = require("../controllers/qrcode.controller");
var router = (0, express_1.Router)();
router.get("/qrcode/generate", qrcode_controller_1.default.generateQrCode);
router.get("/scan/:id", qrcode_controller_2.default.scanQrCode);
router.get("/scan/download/:id", files_controller_1.default.downloadFile);
exports.default = router;
