"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var express_1 = require("express");
var stats_controller_1 = require("../controllers/stats.controller");
var router = (0, express_1.Router)();
router.get("/user", stats_controller_1.default.getByUser);
router.get("/category", stats_controller_1.default.getByType);
router.get("/scope", stats_controller_1.default.getByScope);
router.get("/time", stats_controller_1.default.getByTime);
exports.default = router;
