"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var express_1 = require("express");
var user_controller_1 = require("../controllers/user.controller");
var router = (0, express_1.Router)();
router.get("/", user_controller_1.default.getUsers);
router.get("/:id", user_controller_1.default.getUser);
router.post("/create", user_controller_1.default.checkRole, user_controller_1.default.createUser);
router.put("/:id", user_controller_1.default.checkRole, user_controller_1.default.updateUser);
router.delete("/:id", user_controller_1.default.checkRole, user_controller_1.default.deleteUser);
exports.default = router;
