"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var express_1 = require("express");
var dotenv_1 = require("dotenv");
var users_router_1 = require("./routes/users.router");
var auth_router_1 = require("./routes/auth.router");
var category_router_1 = require("./routes/category.router");
var document_router_1 = require("./routes/document.router");
var files_router_1 = require("./routes/files.router");
var qrcode_router_1 = require("./routes/qrcode.router");
var stats_router_1 = require("./routes/stats.router");
var os_1 = require("os");
dotenv_1.default.config();
require("./database/connection");
var jwt_util_1 = require("./utils/jwt.util");
var scope_router_1 = require("./routes/scope.router");
var app = (0, express_1.default)();
var port = process.env.PORT || 3000;
var apiRoot = process.env.ROOT || "/api/v1";
app.use(express_1.default.json());
app.use(express_1.default.urlencoded({ extended: true }));
app.use(express_1.default.static("public"));
app.set("view engine", "pug");
app.set("views", "public/views");
app.use("/", qrcode_router_1.default);
app.use("".concat(apiRoot, "/auth"), auth_router_1.default);
app.use(jwt_util_1.default.middleware);
app.use("".concat(apiRoot, "/user"), users_router_1.default);
app.use("".concat(apiRoot, "/category"), category_router_1.default);
app.use("".concat(apiRoot, "/scope"), scope_router_1.default);
app.use("".concat(apiRoot, "/document"), document_router_1.default);
app.use("".concat(apiRoot, "/files"), files_router_1.default);
app.use("".concat(apiRoot, "/statistic"), stats_router_1.default);
app.listen(port, "0.0.0.0", function () {
    console.log(`Server is running on http://0.0.0.0:${port}`);
});
